# Generated by Django 6.1.1 on 2026-09-21 17:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaintenanceState",
            fields=[
                (
                    "key",
                    models.CharField(
                        default="worker",
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("oldest_overdue_seconds", models.FloatField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=240)),
                ("reconciliation_count", models.PositiveBigIntegerField(default=0)),
                ("due_work_count", models.PositiveBigIntegerField(default=0)),
                ("notification_wake_count", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_digest", models.BinaryField(max_length=32, unique=True)),
                ("accepted_at_ms", models.JSONField(default=list)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
    ]
