# Generated by Django 6.1.1 on 2026-09-21 17:36

import uuid

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from tunnels.migrations.sql.guards import (
    create_search_index,
    drop_search_index,
    install_guards,
    remove_guards,
)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=80)),
                ("target_type", models.CharField(max_length=80)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agents.agentcredential",
                    ),
                ),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("label", models.CharField(blank=True, max_length=160)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=24,
                    ),
                ),
                ("next_sequence", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "retention_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "closed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "delete_after",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("close_reason", models.CharField(blank=True, max_length=32)),
                (
                    "final_sequence",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("content_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_cycles",
                        to="agents.agentcredential",
                    ),
                ),
            ],
            options={
                "ordering": ["tunnel_id", "number"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sender_name", models.CharField(max_length=120)),
                ("sequence", models.PositiveBigIntegerField()),
                ("depth", models.PositiveIntegerField()),
                (
                    "payload_type",
                    models.CharField(choices=[("text", "Text"), ("json", "JSON")], max_length=8),
                ),
                ("text_payload", models.TextField(blank=True, null=True)),
                ("json_payload", models.TextField(blank=True, null=True)),
                ("byte_count", models.PositiveIntegerField()),
                ("content_digest", models.BinaryField(max_length=32)),
                ("correlation_id", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="tunnels.cycle",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="replies",
                        to="tunnels.message",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_messages",
                        to="agents.agentcredential",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.AddField(
            model_name="cycle",
            name="root_message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="root_of_cycle",
                to="tunnels.message",
            ),
        ),
        migrations.CreateModel(
            name="Tunnel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=160)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dormant", "Dormant"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("next_cycle_number", models.PositiveIntegerField(default=1)),
                ("next_event_position", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dormant_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "retired_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tunnels",
                        to="agents.agentcredential",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="tunnel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="tunnels.tunnel",
            ),
        ),
        migrations.AddField(
            model_name="cycle",
            name="tunnel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cycles",
                to="tunnels.tunnel",
            ),
        ),
        migrations.CreateModel(
            name="ActivityCheckpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_event_position", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_checkpoints",
                        to="agents.agentcredential",
                    ),
                ),
                (
                    "tunnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="tunnels.tunnel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TunnelAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address_digest", models.BinaryField(max_length=32)),
                ("generation", models.PositiveIntegerField(default=1)),
                (
                    "state",
                    models.CharField(
                        choices=[("current", "Current"), ("retired", "Retired")],
                        default="current",
                        max_length=12,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "retired_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("retirement_reason", models.CharField(blank=True, max_length=32)),
                (
                    "tunnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="tunnels.tunnel",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TunnelEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveBigIntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("message_posted", "Message posted"),
                            ("cycle_closed", "Cycle closed"),
                            ("tunnel_dormant", "Tunnel dormant"),
                            ("cycle_started", "Cycle started"),
                            ("address_rotated", "Address rotated"),
                            ("tunnel_retired", "Tunnel retired"),
                        ],
                        max_length=24,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="tunnels.cycle",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="tunnels.message",
                    ),
                ),
                (
                    "tunnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tunnels.tunnel",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operation", models.CharField(max_length=120)),
                ("key_digest", models.BinaryField(max_length=32)),
                ("request_digest", models.BinaryField(max_length=32)),
                ("response", models.JSONField(default=dict)),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                (
                    "derivation_nonce",
                    models.BinaryField(blank=True, max_length=32, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_records",
                        to="agents.agentcredential",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("credential", "operation", "key_digest"),
                        name="unique_idempotency_key_per_operation",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageMention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=120)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message_mentions",
                        to="agents.agentcredential",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentions",
                        to="tunnels.message",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "credential"),
                        name="unique_mention_per_message",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tunnel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("retired_at__isnull", True),
                        ("state__in", ["active", "dormant"]),
                    ),
                    models.Q(("retired_at__isnull", False), ("state", "retired")),
                    _connector="OR",
                ),
                name="tunnel_retirement_state_matches",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["cycle", "parent", "sequence"], name="message_reply_order"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["tunnel", "created_at"], name="message_tunnel_activity"),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("json_payload__isnull", True),
                        ("payload_type", "text"),
                        ("text_payload__isnull", False),
                    ),
                    models.Q(
                        ("json_payload__isnull", False),
                        ("payload_type", "json"),
                        ("text_payload__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="message_has_one_payload_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("byte_count__lte", 65536)),
                name="message_byte_count_at_most_64k",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("cycle", "sequence"), name="unique_message_sequence_per_cycle"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("cycle",),
                name="one_root_per_cycle",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("depth", 0), ("parent__isnull", True)),
                    models.Q(("depth__gt", 0), ("parent__isnull", False)),
                    _connector="OR",
                ),
                name="message_root_depth_matches",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(("depth__lte", 128)),
                name="message_depth_at_most_128",
            ),
        ),
        migrations.AddConstraint(
            model_name="cycle",
            constraint=models.UniqueConstraint(
                fields=("tunnel", "number"), name="unique_cycle_number_per_tunnel"
            ),
        ),
        migrations.AddConstraint(
            model_name="cycle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("tunnel",),
                name="one_active_cycle_per_tunnel",
            ),
        ),
        migrations.AddConstraint(
            model_name="cycle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("closed_at__isnull", True),
                        ("final_sequence__isnull", True),
                        ("state", "active"),
                    ),
                    models.Q(
                        ("closed_at__isnull", False),
                        ("final_sequence__isnull", False),
                        ("state__in", ["closed", "deleted"]),
                    ),
                    _connector="OR",
                ),
                name="cycle_active_close_state_matches",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitycheckpoint",
            constraint=models.UniqueConstraint(
                fields=("tunnel", "credential"),
                name="one_checkpoint_per_credential_tunnel",
            ),
        ),
        migrations.AddConstraint(
            model_name="tunneladdress",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("retired_at__isnull", True), ("state", "current")),
                    models.Q(("retired_at__isnull", False), ("state", "retired")),
                    _connector="OR",
                ),
                name="tunnel_address_retirement_matches",
            ),
        ),
        migrations.AddConstraint(
            model_name="tunneladdress",
            constraint=models.UniqueConstraint(
                fields=("address_digest",), name="unique_tunnel_address"
            ),
        ),
        migrations.AddConstraint(
            model_name="tunneladdress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "current")),
                fields=("tunnel",),
                name="one_current_address_per_tunnel",
            ),
        ),
        migrations.AddConstraint(
            model_name="tunneladdress",
            constraint=models.UniqueConstraint(
                fields=("tunnel", "generation"),
                name="unique_address_generation_per_tunnel",
            ),
        ),
        migrations.AddConstraint(
            model_name="tunnelevent",
            constraint=models.UniqueConstraint(
                fields=("tunnel", "position"), name="unique_event_position_per_tunnel"
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(create_search_index, drop_search_index)],
            state_operations=[
                migrations.AddIndex(
                    model_name="message",
                    index=django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.search.SearchVector(
                            "text_payload", "json_payload", config="simple"
                        ),
                        name="message_content_search",
                    ),
                ),
            ],
        ),
        migrations.RunPython(install_guards, remove_guards),
    ]
