# Generated by Django 6.1.1 on 2026-10-09 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_admincredential_adminoperation"),
        ("tunnels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="actor_admin_credential",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.admincredential",
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="channel",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
