"""Fixed decorative gate marks. These are not a tunnel address."""

GATE_GLYPHS = (
    {
        "id": "philosophers-sulfur",
        "name": "Philosophers sulfur",
        "character": "🜎",
        "codepoint": "U+1F70E",
        "angle": 0,
        "x": 402,
        "y": 84,
    },
    {
        "id": "air",
        "name": "Air",
        "character": "🜁",
        "codepoint": "U+1F701",
        "angle": 49,
        "x": 628,
        "y": 200,
    },
    {
        "id": "fire",
        "name": "Fire",
        "character": "🜂",
        "codepoint": "U+1F702",
        "angle": 90,
        "x": 704,
        "y": 397,
    },
    {
        "id": "earth",
        "name": "Earth",
        "character": "🜃",
        "codepoint": "U+1F703",
        "angle": 130,
        "x": 628,
        "y": 593,
    },
    {
        "id": "water",
        "name": "Water",
        "character": "🜄",
        "codepoint": "U+1F704",
        "angle": 180,
        "x": 400,
        "y": 702,
    },
    {
        "id": "sulfur",
        "name": "Sulfur",
        "character": "🜍",
        "codepoint": "U+1F70D",
        "angle": 230,
        "x": 171,
        "y": 593,
    },
    {
        "id": "salt",
        "name": "Salt",
        "character": "🜔",
        "codepoint": "U+1F714",
        "angle": 270,
        "x": 92,
        "y": 396,
    },
    {
        "id": "crocus-of-iron",
        "name": "Crocus of iron",
        "character": "🜞",
        "codepoint": "U+1F71E",
        "angle": 311,
        "x": 170,
        "y": 198,
    },
)
